require 'optparse'

def make_opcodes_table(filename)
  opcodes = {}

  File.foreach(filename) do |line|
    # split on #
    parts = line.split('#')
    next if parts[0].size == 0

    text = parts[0].chomp
    next if text.empty?

    words = text.split("\t")

    # must have 2 or 3
    if words.count > 3
      puts 'Bad opcode spec: ' + text
      exit
    end

    mnemonic = words[0]
    # [0] must start with alpha
    char = mnemonic[0]
    unless char.match?(/[A-Za-z]/)
      puts 'Bad mnemonic: ' + mnemonic
      exit
    end
    
    # check no duplicate
    if opcodes.key?(mnemonic)
      puts 'Duplicate mnemonic: ' + mnemonic
      exit
    end

    opcode_text = words[1]

    # [1] must be numeric (octal, hex, dec)
    opcode = opcode_text.to_i(0)

    # [2] if exists must be numeric
    argcount = words[2].to_i || 0

    # store
    opcodes[mnemonic] = { 'op' => opcode, 'sz' => argcount }
  end
  
  opcodes
end

def split_mnemonic(tokens, opcodes)
  return nil, '' if tokens.nil?
  return nil, '' if tokens.empty?

  # look for an entry in table that has all tokens that match beginning of line
  opcodes.each do |big_mnemonic|
    mnem_tokens = big_mnemonic.split(/[\s\,]/).reject(&:empty?)
    mnem_size = mnem_tokens.size

    lim_text_tokens = tokens[0..mnem_size-1]

#    puts 'BIG_M: ' + big_mnemonic + ' mnem_tokens: ' + mnem_tokens.to_s + ' mnem_size: ' + mnem_size.to_s
#    puts 'tokens: ' + tokens.to_s + ' lim_text_tokens: ' + lim_text_tokens.to_s

    if lim_text_tokens == mnem_tokens
      arg_tokens = tokens[mnem_size..-1]

      return big_mnemonic, arg_tokens.join
    end
  end

  # did not find opcode
  puts 'did not match ' + tokens.to_s

  return nil, ''
end

def parse_directive_line(asm_text)
  parts = asm_text.split
  
  directive = parts[0]
  arg_text = ''
  arg_text = parts[1] if parts.size > 0
  
  return directive, arg_text
end

def parse_asm_line(asm_text, opcodes)
  # force a first item for the split
  asm_text = ':' + asm_text if asm_text.match(/^\s/) 
  tokens = asm_text.split(/[\s\,]/).reject(&:empty?)
  
  # drop the forced item to make 'label' empty string
  label = nil
  label = tokens[0] if tokens.size > 0 && tokens[0] != ':'

  tokens.shift   # remove label
  mnemonic, arg_text = split_mnemonic(tokens, opcodes)

  return label, mnemonic, arg_text
end

def format_octal_byte(n)
  s = ''
  
  if n.nil?
    s = '    '
  else
    s = ("%#03o" % n).rjust(4)
  end
  
  s
end

def format_octal_word(n)
  s = ''
  
  if n.nil?
    s = '    '
  else
    s = ("%#06o" % n).rjust(7)
  end
  
  s
end

def format_generated_bytes(opcode, arg_size, arg_value)
  s = format_octal_byte(opcode)
  
  s += ' '
  
  # print LSB of arg
  if arg_size > 0
    s += format_octal_byte(arg_value % 256)
  else
    s += format_octal_byte(nil)
  end
    
  s += ' '

  # print MSB of arg    
  if arg_size > 1
    s += format_octal_byte(arg_value / 256)
  else
    s += format_octal_byte(nil)
  end
  
  s
end

def format_asm_line(label, mnemonic, arg_text)
  s = '# '
  
  if label.nil?
    s += '        '
  else
    s += label.ljust(8)
  end

  s += ' ' + mnemonic.sub(' ', "\t")

  unless arg_text.empty?
    if mnemonic.include?(' ')
      s += ','
    else
      s += "\t"
    end

    s += arg_text
  end
  
  s
end

def format_output(address, opcode, arg_size, arg_value, label, mnemonic, arg_text, verbose)
  s = ''

  # print address
  s += format_octal_word(address) + ': ' if verbose

  # print generated bytes
  s += format_generated_bytes(opcode, arg_size, arg_value)
    
  # print source line
  s += ' '
  s += format_asm_line(label, mnemonic, arg_text)
end

def format_nongen_output(label, comment, address, verbose)
  s = ''
  
  if label.nil?
    # no label means no address, just spaces (and only then if a comment)
    if comment.size > 0
      s += '         ' if verbose
      s += '               #'
    end
  else
    # print address and label
    s += format_octal_word(address) + ': ' if verbose
    s += '               # ' + label
  end
  
  s
end

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ruby my_app_options.rb [options]"

  opts.on("-o", "--opcodes NAME", "File name for opcodes table") do |v|
    options[:opcodes_name] = v
  end

  opts.on("-l", "--labels NAME", "File name for label values") do |v|
    options[:labels_name] = v
  end

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

opcodes_table_filename = options[:opcodes_name]

if opcodes_table_filename.nil?
  puts "opcodes table required"
  exit
end

opcodes_table = make_opcodes_table(opcodes_table_filename)

verbose = options[:verbose]
address = 0
labels = {}

# for each line in input
while line = gets
  chomped = line.chomp
  next if line.empty?

  # split on comment; take only first part
  split_line = chomped.split("#")

  asm_text = ''
  asm_text = split_line[0] if split_line.size > 0

  comment = ''
  comment = split_line[1] if split_line.size > 1

  unless asm_text.empty?
    if asm_text[0] == '.'
      # process directive
      directive, arg_text = parse_directive_line(asm_text)
      
      if directive == '.address'
        address = arg_text.to_i(0)
        
        print directive + "\t" + arg_text
      else
        puts 'unknown directive ' + directive
      end
    else
      # process code
      label, mnemonic, arg_text = parse_asm_line(asm_text, opcodes_table.keys)

      unless label.nil?
        labels[label] = address
      end

      arg_value = 0
      arg_value = 0 # do lookup in pass 2

      if mnemonic.nil?
        print format_nongen_output(label, comment, address, verbose)
      else
        opcode_spec = opcodes_table[mnemonic]

        if opcode_spec.nil?
          puts 'Unknown mnemonic: ' + mnemonic
          exit
        end

        opcode = opcode_spec['op']
        arg_size = opcode_spec['sz'] || 0

        print format_output(address, opcode, arg_size, arg_value, label, mnemonic, arg_text, verbose)

        address += 1
        address += arg_size
      end
    end
  end

  # print comment (if any)
  print ' #' + comment if comment.size > 0

  puts
end

# for pass 1, print labels and values 
labels.each do |label, address|
  puts label + ': ' + format_octal_word(address)
end

