require 'optparse'

class AbsRelValue
  attr_reader :value, :is_rel

  def initialize(value, is_rel)
    # value is numeric
    # is_rel.is_a?(TrueClass) || is_rel.is_a?(FalseClass)

    @value = value
    @is_rel = is_rel
  end

  def two_bytes
    [@value % 256, @value / 256]
  end
end

def make_opcodes_table(filename)
  opcodes = {}

  File.foreach(filename) do |line|
    # split on #
    parts = line.split('#')
    next if parts[0].size == 0

    text = parts[0].chomp
    next if text.empty?

    words = text.split("\t")

    # must have 2 or 3
    if words.count > 3
      puts 'Bad opcode spec: ' + text
      exit
    end

    mnemonic = words[0]
    # [0] must start with alpha
    char = mnemonic[0]
    unless char.match?(/[A-Za-z]/)
      puts 'Bad mnemonic: ' + mnemonic
      exit
    end
    
    # check no duplicate
    if opcodes.key?(mnemonic)
      puts 'Duplicate mnemonic: ' + mnemonic
      exit
    end

    opcode_text = words[1]

    # [1] must be numeric (octal, hex, dec)
    opcode = opcode_text.to_i(0)

    # [2] if exists must be numeric
    argcount = words[2].to_i || 0

    # store
    opcodes[mnemonic] = { 'op' => opcode, 'sz' => argcount }
  end
  
  opcodes
end

def read_symbols_file(filename)
  labels = {}
  equates = {}
  symbols = {}

  File.foreach(filename) do |line|
    # split on #
    parts = line.split('#')
    next if parts[0].size == 0

    text = parts[0].chomp
    next if text.empty?

    words = text.split("\t")

    # must have 2 or 3
    if words.count > 3
      puts 'Bad label spec: ' + text
      exit
    end
    
    if words[0] == '.label'
      symbol = words[1]
      value = words[2].to_i(0)
      labels[symbol] = value
      abs_rel_value = AbsRelValue.new(value, true)
      symbols[symbol] = abs_rel_value
    end
    
    if words[0] == '.equate'
      symbol = words[1]
      value = words[2].to_i(0)
      equates[words[1]] = value
      abs_rel_value = AbsRelValue.new(value, false)
      symbols[symbol] = abs_rel_value
    end
  end
  
  [labels, equates, symbols]
end

def split_mnemonic(tokens, opcodes)
  return nil, '' if tokens.nil?
  return nil, '' if tokens.empty?

  # look for an entry in table that has all tokens that match beginning of line
  opcodes.each do |big_mnemonic|
    mnem_tokens = big_mnemonic.split(/[\s\,]/).reject(&:empty?)
    mnem_size = mnem_tokens.size

    lim_text_tokens = tokens[0..mnem_size-1]

#    puts 'BIG_M: ' + big_mnemonic + ' mnem_tokens: ' + mnem_tokens.to_s + ' mnem_size: ' + mnem_size.to_s
#    puts 'tokens: ' + tokens.to_s + ' lim_text_tokens: ' + lim_text_tokens.to_s

    if lim_text_tokens == mnem_tokens
      arg_tokens = tokens[mnem_size..-1]

      return big_mnemonic, arg_tokens.join
    end
  end

  # did not find opcode
  puts 'did not match ' + tokens.to_s

  return nil, ''
end

def parse_directive_line(asm_text)
  # does not allow for quoted space chars or strings
  parts = asm_text.split
  
  directive = parts.shift
  
  return directive, parts
end

def parse_asm_line(asm_text, opcodes)
  # force a first item for the split
  asm_text = ':' + asm_text if asm_text.match(/^\s/) 
  tokens = asm_text.split(/[\s\,]/).reject(&:empty?)
  
  # drop the forced item to make 'label' empty string
  label = nil
  label = tokens[0] if tokens.size > 0 && tokens[0] != ':'

  tokens.shift   # remove label
  mnemonic, arg_text = split_mnemonic(tokens, opcodes)

  return label, mnemonic, arg_text
end

def format_octal_byte(n)
  s = ''
  
  unless n.nil?
    s = ("%#03o" % n)
  end
  
  s.rjust(4)
end

def format_octal_word(n)
  s = ''
  
  unless n.nil?
    s = ("%#06o" % n)
  end
  
  s.rjust(7)
end

def format_generated_bytes(opcode, arg_size, arg_value)
  s = format_octal_byte(opcode)
  
  s += ' '
  
  # print LSB of arg
  if arg_size > 0
    s += format_octal_byte(arg_value % 256)
  else
    s += format_octal_byte(nil)
  end
    
  s += ' '

  # print MSB of arg    
  if arg_size > 1
    s += format_octal_byte(arg_value / 256)
  else
    s += format_octal_byte(nil)
  end
  
  s
end

def format_asm_line(label, mnemonic, arg_text)
  s = '# '
  
  if label.nil?
    s += '        '
  else
    s += label.ljust(8)
  end

  s += ' ' + mnemonic.sub(' ', "\t")

  unless arg_text.empty?
    if mnemonic.include?(' ')
      s += ','
    else
      s += "\t"
    end

    s += arg_text
  end
  
  s
end

def format_output(offset, opcode, arg_size, arg_value, label, mnemonic, arg_text)
  s = ''

  # print offset
  s += format_octal_word(offset) + ': '

  # print generated bytes
  s += format_generated_bytes(opcode, arg_size, arg_value)
    
  # print source line
  s += ' '
  s += format_asm_line(label, mnemonic, arg_text)
end

def format_nongen_output(label, comment, offset)
  s = ''
  
  if label.nil?
    # no label means no offset, just spaces (and only then if a comment)
    if comment.size > 0
      s += '         '
      s += '               #'
    end
  else
    # print offset and label
    s += format_octal_word(offset) + ': '
    s += '               # ' + label
  end
  
  s
end

def format_bytes_output(offset, values)
  s = ''
  
  # print offset
  if offset.nil?
    s += '       : '
  else
    s += format_octal_word(offset) + ': '
  end

  # print generated bytes
  values.each do |value|
    s += format_octal_byte(value)
    s += ' '
  end
  
  s
end

def op_add(a, b)
  # abs + abs => abs
  # abs + rel => rel
  # rel + abs => rel
  # rel + rel => error

  raise Exception('two rel values for plus') if a.is_rel && b.is_rel

  is_rel = false
  is_rel = true if a.is_rel
  is_rel = true if b.is_rel

  AbsRelValue.new(a.value + b.value, is_rel)
end

def op_subtract(a, b)
  # abs - abs => abs
  # abs - rel => rel
  # rel - abs => rel
  # rel - rel => abs

  is_rel = false
  is_rel = true if a.is_rel != b.is_rel

  AbsRelValue.new(a.value - b.value, is_rel)
end

def op_multiply(a, b)
  # abs * abs => abs
  # abs * rel => error
  # rel * abs => error
  # rel * rel => error

  raise Exception('two rel values for multiply') if a.is_rel || b.is_rel

  is_rel = false

  AbsRelValue.new(a.value * b.value, is_rel)
end

def op_divide(a, b)
  # check for divide by zero
  # abs / abs => abs
  # abs / rel => error
  # rel / abs => error
  # rel / rel => error

  raise Exception('two rel values for divide') if a.is_rel || b.is_rel

  is_rel = false

  AbsRelValue.new(a.value / b.value, is_rel)
end

def eval_rpn(tokens, offset, symbols)
  # return a list of values
  values = []
  
  tokens.each do |token|
    case token
    when '+'
      # check at least two values
      # pop two values
      b = values.pop
      a = values.pop
      # execute
      result = op_add(a, b)
      # push result
      values << result
    when '-'
      # check at least two values
      # pop two values
      b = values.pop
      a = values.pop
      # execute
      result = op_subtract(a, b)
      # push result
      values << result
    when '*'
      # check at least two values
      # pop two values
      b = values.pop
      a = values.pop
      # execute
      result = op_multiply(a, b)
      # push result
      values << result
    when '/'
      # check at least two values
      # pop two values
      b = values.pop
      a = values.pop
      # execute
      result = op_divide(a, b)
      # push result
      values << result
    when /^\d+$/
      # convert
      value = token.to_i(0)
      # push
      values << AbsRelValue.new(value, false)
    when /\A[A-Z][A-Z0-9_]*\z/
      # look up value
      value = symbols[token]
      # push
      values << value
    when '.offset'
      values << AbsRelValue.new(offset, true)
    else
      puts "unknown token: '" + token + "'"
    end
  end
  
  values
end

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ruby my_app_options.rb [options]"

  opts.on("-o", "--opcodes NAME", "File name for opcodes table") do |v|
    options[:opcodes_name] = v
  end

  opts.on("-l", "--list NAME", "File name for list output") do |v|
    options[:list_name] = v
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

opcodes_table_filename = options[:opcodes_name]

if opcodes_table_filename.nil?
  puts "opcodes table required"
  exit
end

opcodes_table = make_opcodes_table(opcodes_table_filename)

list_output_filename = options[:list_name]

symbols = {}
references = {}

puts '.relocatable'

puts '.code'

offset = 0
word_count = 0

list_lines = []

# for each line in input
while line = gets
  chomped = line.chomp
  next if line.empty?

  # split on comment; take only first part
  split_line = chomped.split("#")

  asm_text = ''
  asm_text = split_line[0] if split_line.size > 0

  comment = ''
  comment = split_line[1] if split_line.size > 1

  list_line = ''

  unless asm_text.empty?
    if asm_text[0] == '.'
      # process directive
      directive, parts = parse_directive_line(asm_text)
      
      case directive
      when '.equate'
        # parse label, expression (tokens separated by whitespace)
        label = parts.shift
        # evaluate expression in RPN
        values = eval_rpn(parts, offset, symbols)
        value = values[0]
        bytes = value.two_bytes
        bytes_s = format_octal_word(bytes)
        list_line = '         ' + bytes_s + "\t# " + directive + ' ' + label + ' ' + parts.to_s
        # store value in equates table (check for inconsistency)
        symbols[label] = value
      when '.word'
        # parse expression
        # evaluate parts as RPN
        values = eval_rpn(parts, offset, symbols)
        value = values[0]
        # gen 2 bytes (low byte first)
        bytes = value.two_bytes
        bytes_s = format_bytes_output(offset, bytes)
        list_line = bytes_s + "\t# " + directive + "\t" + parts.to_s

        if value.is_rel
          if parts.size == 1
            label = parts[0]
          else
            label = 'word_' + word_count.to_s
          end

          symbols[label] = value
          references[offset] = label
        end

        offset += values.size * 2
        word_count += 1
      else
        puts 'unknown directive: ' + directive
        exit
      end
    else
      # process code
      label, mnemonic, arg_text = parse_asm_line(asm_text, opcodes_table.keys)

      symbols[label] = AbsRelValue.new(offset, true) unless label.nil?

      arg_value = 0

      if mnemonic.nil?
        list_line = format_nongen_output(label, comment, offset)
      else
        opcode_spec = opcodes_table[mnemonic]

        if opcode_spec.nil?
          puts 'unknown mnemonic: ' + mnemonic
          exit
        end

        opcode = opcode_spec['op']
        arg_size = opcode_spec['sz'] || 0

        # add to code segment
        list_line = format_output(offset, opcode, arg_size, arg_value, label, mnemonic, arg_text)

        if arg_size == 2
          if arg_text.match(/\A[A-Z][A-Z0-9_]*\z/)
            offset_ref = offset + 1  # skip over the opcode
            references[offset_ref] = arg_text
          end
        end

        offset += 1
        offset += arg_size
      end
    end
  end

  # print comment (if any)
  list_line += ' #' + comment if comment.size > 0

  list_lines << list_line
end

unless list_output_filename.nil?
  File.open(list_output_filename, "w") do |file|
    list_lines.each do |line|
      file.puts(line)
    end
  end
end


puts '.symbols'

symbols.each do |symbol, abs_rel_value|
  value_s = format_octal_word(abs_rel_value.value)
  abs_or_rel = "abs"
  abs_or_rel = "rel" if abs_rel_value.is_rel
  puts abs_or_rel + "\t" + symbol + "\t" + value_s
end

puts '.references'

references.each do |offset, symbol|
  offset_s = format_octal_word(offset)
  puts offset_s + "\t" + symbol
end

puts '.end'
